# Generated by Django 5.0.1 on 2024-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prof', models.TextField()),
                ('mob', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('facebook', models.CharField(max_length=250)),
                ('instagram', models.CharField(max_length=250)),
                ('linkedin', models.CharField(max_length=250)),
                ('twitter', models.CharField(max_length=250)),
            ],
        ),
    ]
