# Generated by Django 5.0.1 on 2024-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_endis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
