# Generated by Django 5.0.1 on 2024-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_profile_facebook_endis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_endis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_endis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_endis',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
