# Generated by Django 5.0.1 on 2024-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_profile_prof_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='our_services',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
