# Generated by Django 5.0.1 on 2024-07-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0009_profile_profile_image_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='google_endis',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_endis',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_endis',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_endis',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
