# Generated by Django 5.0.1 on 2024-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0012_profile_genaral_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genaral_link2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='genaral_link3',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='genaral_link_endis2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='genaral_link_endis3',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='genaral_link_name2',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='genaral_link_name3',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
