# Generated by Django 5.0.1 on 2024-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0013_profile_genaral_link2_profile_genaral_link3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='brochure',
            field=models.ImageField(default=0, upload_to='brochures/'),
            preserve_default=False,
        ),
    ]
